# frozen_string_literal: true

source "https://rubygems.org"
gem "jekyll", '3.10.0'
gem "github-pages"

group :jekyll_plugins do
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
  gem 'csv'
  gem 'base64'
  gem 'bigdecimal'
  gem 'kramdown-parser-gfm'
end

# gem "rails"
